---
- name: Converge
  hosts: all
  roles:
    - role: supertarto.logrotate

  vars:
    - name: mail
      paths:
        - "/var/log/mail/mail.info"
        - "/var/log/mail/mail.warn"
        - "/var/log/mail/mail.err"
      options:
        - "rotate 52"
        - "weekly"
        - "compress"
      scripts:
        postrotate: invoke-rc.d rsyslog rotate > /dev/null
